name: update blog when changes

on:
  push:
    branches: [main]
    paths:
      - 'blog/**'    
  workflow_dispatch:
#   schedule:
# #     - cron: "25 */4 * * *"
#     - cron: "59 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FAKE_HASH: "Automated deployment @ $(date '+%Y-%m-%d %H:%M:%S') Asia/Shanghai"
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Setup GIT user
        uses: fregante/setup-git-user@v1
      -
        name: install requirements
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          pip install  -r dev.txt
      -
        name: prepare fingerprint
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          python fingerprint.py
      -
        name: prepare blogs markdown
        run: |
          pip install requests && python main.py
          echo "$(cat README.md)" >> $GITHUB_STEP_SUMMARY          
      -
        name: Push
        run: |
          git add .
          git commit -m "${{ env.FAKE_HASH }}" 
          git push -f
